server:
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
  port: 9876
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cmfz?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: utf-8
    multipart:
      max-file-size: 100MB
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity

